name: demandium_serviceman
description: A new Flutter project.

publish_to: 'none' #

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  intl: ^0.19.0
  http: ^1.2.1
  path: ^1.9.0
  path_provider: ^2.1.3
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.1.0
  firebase_core: ^3.7.0
  firebase_messaging: ^15.1.4
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  geolocator: ^13.0.1
  url_launcher: ^6.3.1
  country_code_picker: ^3.1.0
  pin_code_fields: ^8.0.1
  flutter_widget_from_html_core: ^0.15.2
  shimmer_animation: ^2.2.1
  fl_chart: ^0.69.0
  dotted_border: ^2.1.0
  flutter_local_notifications: ^18.0.0
  file_picker: ^8.1.3
  pdf: ^3.11.1
  #open_file_plus: ^3.4.1+1
  flutter_downloader: ^1.11.8
  permission_handler: ^11.3.1
  printing: ^5.13.2
  flutter_switch: ^0.3.2
  photo_view: ^0.15.0
  scroll_to_index: any
  phone_numbers_parser: ^9.0.1
  firebase_auth: ^5.3.1
  carousel_slider: ^5.0.0
  open_file_plus: ^3.4.1+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/font/Roboto-Light.ttf
          weight: 300
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
